### ISSUE TITLE
Multiple css selectors not allowed in :global() feilds.

### ISSUE THREAD

**Issue by divinepaul** [joshnuss/svelte-codemirror#2]
The demo code or the REPL doesn't work because of multiple CSS selectors in :global() styles.

Error:
`:global(...) must contain a single selector (Component.svelte:84:0)`

**Comment by joshnuss** [comment]
Good catch, multiple selectors are no longer allowed for :global.

Feel free to open a PR to split them.
Or I'll fix it next time I use this repo (could be a few months)

**Comment by joshnuss** [comment]
Fixed in 33ccdd4119d9ccbdcada5c601ebb4549b1629999
